import type { Metadata } from "next";
import { ThemeProvider } from "@/components/providers/theme-provider.tsx";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
        <div className="block md:hidden w-full h-8 fixed top-0 left-0 inset-y-0 z-50">
          <Navbar/>
        </div>
        <div className="hidden md:block w-60 h-full fixed top-0 left-0 inset-y-0 z-50">
          <Sidebar />
        </div>
        <main className="pt-10 md:pt-0 md:pl-60 h-full z-10">{children}</main>
      </ThemeProvider>
  );
}
